module.exports = {
  ok: "success",
  userRegister: "Register successfull",
  userLogin: "Login successfull",
  productAdded: "Product added successfully",
  giftAdded: "Gift added successfully",
  outOfStock: "Product is currently out of stock",
  NoSoldouts: "Currently their is no soldout campaign",
  orderCreated: "Order created successfully",
  NotFound: "Record Not Found",
  DriverNotFound: "Driver Not Found",
  OrderNotFound: "Order Not Found",
  emailAlreadyExist: "Record Already Exist",
  updateSuccess: "Updated successfull",
  deleteSuccess: "Deleted successfull",
  incorrectPassword: "Incorrect Email or Password",
  incorrectOldPassword: "Your password is incorrect",
  removeFromWishlist: "Campaign removed from wishlist",
  addToCart: "Added to cart successfully",
  removeFromCart: "Campaign removed from cart",
  alreadyInCart: "Campaign is aready in cart",
  addToWishlist: "Campaign added to wishlist",
  passwordUpdate: "Password update successfull",
  emailSent: "Mail has been sent",
  serverError: "Internal Server Error",
  validationErrors: "Validation Errors",
  tokenInvalid: "Token is invalid",
  authorizationError: "User not authorized"
};
